//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net__调用_webService_服务引用和动态代理_.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAge(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAge", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetAgeAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void HelloWorld1(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld1", ReplyAction="*")]
        System.Threading.Tasks.Task HelloWorld1Async(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld2(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorld2Async(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : net__调用_webService_服务引用和动态代理_.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<net__调用_webService_服务引用和动态代理_.ServiceReference1.WebService1Soap>, net__调用_webService_服务引用和动态代理_.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string GetAge(string id) {
            return base.Channel.GetAge(id);
        }
        
        public System.Threading.Tasks.Task<string> GetAgeAsync(string id) {
            return base.Channel.GetAgeAsync(id);
        }
        
        public void HelloWorld1(string name) {
            base.Channel.HelloWorld1(name);
        }
        
        public System.Threading.Tasks.Task HelloWorld1Async(string name) {
            return base.Channel.HelloWorld1Async(name);
        }
        
        public string HelloWorld2(string name) {
            return base.Channel.HelloWorld2(name);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorld2Async(string name) {
            return base.Channel.HelloWorld2Async(name);
        }
    }
}
